/* ------------------------------------------------------------------------------
<auto-generated>
    This file was generated by Sitefinity CLI v1.1.0.9
</auto-generated>
------------------------------------------------------------------------------ */

using System;
using System.Web.Mvc;
using Telerik.Sitefinity.Mvc;
using Telerik.Sitefinity.Libraries.Model;
using Progress.Sitefinity.Renderer.Entities.Content;

namespace TheTrainingboss.SFADVDev.Mvc.Models
{
	public enum Enumeration
	{
		Value1,
		Value2,
		Value3
	}
	public class MyWidgetModel
	{
		public string Message { get; set; }
		public bool Flag { get; set; }
		public Enumeration Enum { get; set; }
		public int Number { get; set; }
		public DateTime MyDate { get; set; }
		public string Images { get; set; }
	}
}