/* ------------------------------------------------------------------------------
<auto-generated>
    This file was generated by Sitefinity CLI v1.1.0.9
</auto-generated>
------------------------------------------------------------------------------ */

using System;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;
using Telerik.Sitefinity.DynamicModules.Model;
using Telerik.Sitefinity.Model;
using Telerik.Sitefinity.Mvc;
using Telerik.Sitefinity.RelatedData;
using Telerik.Sitefinity.Libraries.Model;

namespace TheTrainingboss.SFADVDev.Mvc.Models
{
	public class SliderMVCModel
	{
        public List<ParallaxItem> ParallaxItems
        {
            get;
            private set;
        }
        public class ParallaxItem
        {
            public string Title { get; set; }
            public string Details { get; set; }
            public string ItemUrl { get; set; }
            public string ImageUrl { get; set; }
            public string ImageAlt { get; set; }
        }
        public SliderMVCModel(IQueryable<DynamicContent> items)
        {
            this.ParallaxItems = SetParallaxItems(items);
        }

        private List<ParallaxItem> SetParallaxItems(IQueryable<DynamicContent> items)
        {
            List<ParallaxItem> parallaxItems = new List<ParallaxItem>();
            foreach (var item in items)
            {
                ParallaxItem parallaxItem = new ParallaxItem();
                parallaxItem.Title = item.GetValue<Lstring>("Title");
                parallaxItem.Details = item.GetValue<Lstring>("Details");
                IDataItem pageSelectorItem = item.GetRelatedItems("Url").FirstOrDefault();
                parallaxItem.ItemUrl = pageSelectorItem.GetDefaultUrl();
                //getting the image
                Image imageField = item.GetRelatedItems<Image>("Photo").SingleOrDefault();
                //getting the url
                parallaxItem.ImageUrl = imageField.Url;
                parallaxItem.ImageAlt = imageField.AlternativeText;
                parallaxItems.Add(parallaxItem);
            }

            return parallaxItems;
        }
    }
}