/* ------------------------------------------------------------------------------
<auto-generated>
    This file was generated by Sitefinity CLI v1.1.0.9
</auto-generated>
------------------------------------------------------------------------------ */

using TheTrainingboss.SFADVDev.Mvc.Models;
using System.Web.Mvc;
using Telerik.Sitefinity.Mvc;
using Telerik.Sitefinity.Personalization;
using Telerik.Sitefinity.Modules.News;
using System.Linq;
using Telerik.Sitefinity.GenericContent.Model;

namespace TheTrainingboss.SFADVDev.Mvc.Controllers
{
	[ControllerToolboxItem(Name = "NewsCrud", Title = "News Crud", SectionName = "SFADVDev")]
	public class NewsCrudController : Controller, IPersonalizable
	{
		// GET: NewsCrud
		public ActionResult Index()
		{
			NewsManager nm = NewsManager.GetManager();
			var news = nm.GetNewsItems().Where(n => n.Status == ContentLifecycleStatus.Live);
			var model = new NewsCrudModel(news);
			
			return View(model);
		}
		
        protected override void HandleUnknownAction(string actionName)
        {
            this.ActionInvoker.InvokeAction(this.ControllerContext, "Index");
        }

		
	}
}